version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  app:
    image: node:16-alpine
    container_name: my_next_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://my_mongo_container:27017/englishdb
      NODE_ENV: production
    command: >
      sh -c "npm install && npm run build && npm start"

volumes:
  mongo-data:
